### ISSUE TITLE
how to compile this on windows / please provide binary builds

### ISSUE THREAD

**Issue by basisbit** [astoeckel/acinerella#3]
I am currently looking through the code of acinerella and would like to use it with ffmpeg 3 but don't know how to compile it either on windws or how to compile it on linux for build targets OS X and Windows x86. Could you maybe provide some build instructions for that or alternatively provide the compiled binary files?

Thanks in advance!

**Comment by astoeckel** [comment]
Sorry, I fear I can't help you with this issue. My Windows times are long over now. Theoretically it should be possible to generate a Visual Studio Project with CMake and compile acinerella this way. If this doesn't work, acinerella is just a single .c file -- just create a Visual Studio project containing this file and point the compiler at the FFMpeg headers and binaries.

Please let me know if you have any success, I'll gladly update the README on this topic.

**Comment by lukeIam** [comment]
Compiling on Windows with VS is a bit hacky but working:
- Generate a sln with cMake GUI
- Download the matching ffmpeg dev package from https://ffmpeg.zeranoe.com/builds/
- Add lib and include paths to the project
- Add this to `Additional Dependencies`
```
avcodec.lib
avformat.lib
avutil.lib
swresample.lib
swscale.lib
```
- Set `SAFESEH No (/SAFESEH:NO)`
- Build
