### ISSUE TITLE
GPL vs LGPL

### ISSUE THREAD

**Issue by z505** [astoeckel/acinerella#5]
Did you mean for this to be GPL and not LGPL, as LGPL allows this to be linked in as a library to any program but GPL not?

**Comment by astoeckel** [comment]
Yes, I consciously chose the GPL. The reason for this was that the binary version I provided for Windows back when I initially wrote Acinerella contained ffmpeg compiled in GPL mode, so it really didn't make much sense to choose the LGPL.

But from my current perspective, there is really no reason not to license Acinerella under a more permissive license. I'll think about.

**Comment by astoeckel** [comment]
Changed the license to LGPL 2.1 or later. Sorry for this to take so long.
