### ISSUE TITLE
Internet radio

### ISSUE THREAD

**Issue by dibok** [astoeckel/acinerella#6]
Hi,

Do you have in plans extend library for streaming internet radio? IIRC ffmpeg can stream any web source.

Regards

**Comment by astoeckel** [comment]
No, Acinerella is supposed to solely operate on the stream demultiplexing and decoding layer for in-memory data. Internet radio streaming over HTTP/Icecast is for example implemented in the Audorra library (Pascal), see https://github.com/astoeckel/audorra/blob/master/src/protocols/AuHTTP.pas . (Not saying that anyone should use that old code, but just to demonstrate that it is relatively straight-forward to implement.)
